campusys_pedagogie_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: campusysPedagogieBundle:Default:index }

# Backend
# Universities
campusys_universities_list:
    path: /admin/universities/
    defaults: { _controller: campusysPedagogieBundle:University:admin_index }

campusys_university_edit:
    pattern: /admin/university/edit/{id}
    defaults: { _controller: campusysPedagogieBundle:University:admin_edit }
    
campusys_university_edit_column:
    pattern: /admin/universities/editColumn/{column}/{value}/{id}
    defaults: { _controller: campusysPedagogieBundle:University:admin_edit_column }
    
campusys_university_view:
    pattern: /admin/universities/view/{id}
    defaults: { _controller: campusysPedagogieBundle:University:admin_view }

campusys_university_delete:
    pattern: /admin/university/delete/{id}
    defaults: { _controller: campusysPedagogieBundle:University:admin_delete }

campusys_university_active:
    pattern: /admin/universities/active/{id}
    defaults: { _controller: campusysPedagogieBundle:University:admin_active }

campusys_university_delete_selection:
    pattern: /admin/university/deleteSelection
    defaults: { _controller: campusysPedagogieBundle:University:admin_delete_selection }
    
    
# Campus
campusys_campuses_list:
    path: /admin/campus/
    defaults: { _controller: campusysPedagogieBundle:Campus:admin_index }

campusys_campus_edit:
    pattern: /admin/campus/edit/{id}
    defaults: { _controller: campusysPedagogieBundle:Campus:admin_edit }
    
campusys_campus_edit_column:
    pattern: /admin/campus/editColumn/{column}/{value}/{id}
    defaults: { _controller: campusysPedagogieBundle:Campus:admin_edit_column }
    
campusys_campus_view:
    pattern: /admin/campus/view/{id}
    defaults: { _controller: campusysPedagogieBundle:Campus:admin_view }

campusys_campus_delete:
    pattern: /admin/campus/delete/{id}
    defaults: { _controller: campusysPedagogieBundle:Campus:admin_delete }

campusys_campus_active:
    pattern: /admin/campus/active/{id}
    defaults: { _controller: campusysPedagogieBundle:Campus:admin_active }

campusys_campus_delete_selection:
    pattern: /admin/campus/deleteSelection
    defaults: { _controller: campusysPedagogieBundle:Campus:admin_delete_selection }
    
    

# filière
campusys_filieres_list:
    path: /admin/filiere/
    defaults: { _controller: campusysPedagogieBundle:Filiere:admin_index }

campusys_filiere_edit:
    pattern: /admin/filiere/edit/{id}
    defaults: { _controller: campusysPedagogieBundle:Filiere:admin_edit }
    
campusys_filiere_edit_column:
    pattern: /admin/filiere/editColumn/{column}/{value}/{id}
    defaults: { _controller: campusysPedagogieBundle:Filiere:admin_edit_column }
    
campusys_filiere_view:
    pattern: /admin/filiere/view/{id}
    defaults: { _controller: campusysPedagogieBundle:Filiere:admin_view }

campusys_filiere_delete:
    pattern: /admin/filiere/delete/{id}
    defaults: { _controller: campusysPedagogieBundle:Filiere:admin_delete }

campusys_filiere_active:
    pattern: /admin/filiere/active/{id}
    defaults: { _controller: campusysPedagogieBundle:Filiere:admin_active }

campusys_filiere_delete_selection:
    pattern: /admin/filiere/deleteSelection
    defaults: { _controller: campusysPedagogieBundle:Filiere:admin_delete_selection }
    
    
# Modules
campusys_modules_list:
    path: /admin/module/
    defaults: { _controller: campusysPedagogieBundle:Module:admin_index }

campusys_module_edit:
    pattern: /admin/module/edit/{id}
    defaults: { _controller: campusysPedagogieBundle:Module:admin_edit }
    
campusys_module_edit_column:
    pattern: /admin/module/editColumn/{column}/{value}/{id}
    defaults: { _controller: campusysPedagogieBundle:Module:admin_edit_column }
    
campusys_module_view:
    pattern: /admin/module/view/{id}
    defaults: { _controller: campusysPedagogieBundle:Module:admin_view }

campusys_module_delete:
    pattern: /admin/module/delete/{id}
    defaults: { _controller: campusysPedagogieBundle:Module:admin_delete }

campusys_module_active:
    pattern: /admin/module/active/{id}
    defaults: { _controller: campusysPedagogieBundle:Module:admin_active }

campusys_module_delete_selection:
    pattern: /admin/module/deleteSelection
    defaults: { _controller: campusysPedagogieBundle:Module:admin_delete_selection }
    
    
 # Cours
campusys_courses_list:
    path: /admin/cours/
    defaults: { _controller: campusysPedagogieBundle:Cours:admin_index }

campusys_cours_edit:
    pattern: /admin/cours/edit/{id}
    defaults: { _controller: campusysPedagogieBundle:Cours:admin_edit }
    
campusys_cours_edit_column:
    pattern: /admin/cours/editColumn/{column}/{value}/{id}
    defaults: { _controller: campusysPedagogieBundle:Cours:admin_edit_column }
    
campusys_cours_view:
    pattern: /admin/cours/view/{id}
    defaults: { _controller: campusysPedagogieBundle:Cours:admin_view }

campusys_cours_delete:
    pattern: /admin/cours/delete/{id}
    defaults: { _controller: campusysPedagogieBundle:Cours:admin_delete }

campusys_cours_active:
    pattern: /admin/cours/active/{id}
    defaults: { _controller: campusysPedagogieBundle:Cours:admin_active }

campusys_cours_delete_selection:
    pattern: /admin/cours/deleteSelection
    defaults: { _controller: campusysPedagogieBundle:Cours:admin_delete_selection }
    

 # Semestre
campusys_semestres_list:
    path: /admin/semestre/
    defaults: { _controller: campusysPedagogieBundle:Semestre:admin_index }

campusys_semestre_edit:
    pattern: /admin/semestre/edit/{id}
    defaults: { _controller: campusysPedagogieBundle:Semestre:admin_edit }
    
campusys_semestre_edit_column:
    pattern: /admin/semestre/editColumn/{column}/{value}/{id}
    defaults: { _controller: campusysPedagogieBundle:Semestre:admin_edit_column }
    
campusys_semestre_view:
    pattern: /admin/semestre/view/{id}
    defaults: { _controller: campusysPedagogieBundle:Semestre:admin_view }

campusys_semestre_delete:
    pattern: /admin/semestre/delete/{id}
    defaults: { _controller: campusysPedagogieBundle:Semestre:admin_delete }

campusys_semestre_active:
    pattern: /admin/semestre/active/{id}
    defaults: { _controller: campusysPedagogieBundle:Semestre:admin_active }

campusys_semestre_delete_selection:
    pattern: /admin/semestre/deleteSelection
    defaults: { _controller: campusysPedagogieBundle:Semestre:admin_delete_selection }