parameters:
#    campusys_pedagogie.example.class: campusys\PedagogieBundle\Example

services:
#    campusys_pedagogie.example:
#        class: %campusys_pedagogie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
