security:
    encoders:
        itCertif\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main: 
            entity: { class: campusysPedagogieBundle:University }


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:   ^/login$
            anonymous: true
        main:
            pattern: ^zer/admin
            anonymous: false
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /admin

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

